### ISSUE TITLE
Datasheet for QoE Datasets

### ISSUE THREAD

**Issue by NabajeetBarman** [VQEG/software-tools#17]
If you want to add a new tool, please add the following information:

- **Title:** Datasheet for Subjective and Objective Quality Assessment Datasets
- **Excerpt:** A datasheet template to document the various aspects of QoE datasets.
- **Authors:** 
         `Dr Nabajeet Barman, Kingston University, London, United Kingdom (n.barman@ieee.org, nabajeetbarman4@gmail.com)`
         `Dr Yuriy Reznik, Brightcove Inc, Seattle, USA  (yreznik@brightcove.com)`
         `Prof Maria Martini, Kingston University, London, United Kingdom (m.martini@kingston.ac.uk)`
- **License:**  MIT license
- **Tags:** 
    - `open-source`
    - `datasheet`
    - QoE datasets
- **Category:** one of the following
    - Helper Tools
- **[External Link:** (the link to the website where the tool is hosted)](https://github.com/NabajeetBarman/datasheet-for-qoe-datasets)

Longer description:

Over the years, many subjective and objective quality assessment datasets have been created and made available to the research community. However, there is no standard process for documenting the various aspects of the dataset, such as details about the source sequences, number of test subjects, test methodology, encoding settings, etc. Such information is often of great importance to the end-user of the dataset as it can help them get a quick understanding of the motivation and scope of the dataset. Without such a template, it is left to each reader to collate the information from the relevant publication or website, which is a tedious and time-consuming process. In some cases, the absence of a template to guide the documentation process can result in an unintentional omission of some important information. 

We address this simple but significant gap by proposing a datasheet template for documenting various aspects of subjective and objective quality assessment datasets for multimedia data. The template presented in this work aim to simplify the documentation process for existing and new datasets and improve their reproducibility.

More details can be found in the paper [here](https://drive.google.com/file/d/1E1C8sWk-IYGCmqRRv6tclmtNgtWrhM-8/view?usp=sharing).
The poster presented in QoMEX'23 is available [here.](https://drive.google.com/file/d/1Z0TYObfiS8Jy3a_UExPRax1ERtZJG6eB/view?usp=sharing)

**Comment by slhck** [comment]
Merged, thanks
